# Generated by Django 4.1.4 on 2022-12-16 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_last_action_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="inviting_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пригласивший пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 16, 3, 21, 213468),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 16, 3, 21, 213435),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 16, 3, 21, 217168),
                verbose_name="Время покупки",
            ),
        ),
    ]
