# Generated by Django 4.1.3 on 2022-12-06 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_last_action_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="in_chat",
            field=models.BooleanField(default=False, verbose_name="В чате"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Забанен"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_helper",
            field=models.BooleanField(default=False, verbose_name="Помощник"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 26, 54, 306804),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 26, 54, 306784),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 26, 54, 308626),
                verbose_name="Время покупки",
            ),
        ),
    ]
