# Generated by Django 4.1.3 on 2022-12-06 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_profile_in_chat_profile_is_active_profile_is_blocked_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 30, 44, 522955),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 30, 44, 522936),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 20, 30, 44, 524737),
                verbose_name="Время покупки",
            ),
        ),
    ]
