# Generated by Django 4.1.4 on 2022-12-16 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Имя в Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 1, 25, 175495),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Фамилия в Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 1, 25, 175473),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Username Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 1, 25, 177261),
                verbose_name="Время покупки",
            ),
        ),
    ]
