# Generated by Django 4.1.3 on 2022-12-10 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_last_action_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 10, 38, 19, 991441),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 10, 38, 19, 991419),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 10, 38, 19, 993158),
                verbose_name="Время покупки",
            ),
        ),
    ]
