# Generated by Django 4.1.4 on 2022-12-16 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 55, 1, 937720),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 55, 1, 937700),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_id",
            field=models.BigIntegerField(
                db_index=True, unique=True, verbose_name="ID Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 19, 55, 1, 939612),
                verbose_name="Время покупки",
            ),
        ),
    ]
