# Generated by Django 4.1.3 on 2022-12-10 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_last_action_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="inviting_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пригласивший пользователь",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.subscription",
                verbose_name="Подписка",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 10, 24, 133702),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 10, 24, 133685),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 10, 24, 135537),
                verbose_name="Время покупки",
            ),
        ),
    ]
