# Generated by Django 4.1.4 on 2022-12-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_last_action_date_and_more"),
        ("profiles", "0008_alter_profile_last_action_date_and_more"),
    ]

    operations = []
