# Generated by Django 4.1.3 on 2022-12-10 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_remove_subscription_profile_profile_inviting_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="subscription",
        ),
        migrations.AddField(
            model_name="subscription",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 14, 15, 563588),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 14, 15, 563568),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 14, 15, 567126),
                verbose_name="Время покупки",
            ),
        ),
    ]
