# Generated by Django 4.1.3 on 2022-12-10 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_remove_profile_subscription_subscription_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="displayed",
            field=models.BooleanField(default=True, verbose_name="Отображается"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 48, 3, 115956),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 48, 3, 115937),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 48, 3, 118863),
                verbose_name="Время покупки",
            ),
        ),
    ]
