# Generated by Django 4.1.3 on 2022-12-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_alter_profile_last_action_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="count_actions_in_current_day",
            new_name="_count_actions_in_current_day",
        ),
        migrations.AddField(
            model_name="profile",
            name="_count_actions",
            field=models.IntegerField(
                default=0, verbose_name="Общее количество действий"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="_count_days_in_bot",
            field=models.IntegerField(default=0, verbose_name="Количество дней в боте"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 52, 46, 432732),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 52, 46, 432711),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 52, 46, 434670),
                verbose_name="Время покупки",
            ),
        ),
    ]
