# Generated by Django 4.1.3 on 2022-12-10 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0023_rename_count_actions_in_current_day_profile__count_actions_in_current_day_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="_count_actions",
            new_name="count_actions",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="_count_actions_in_current_day",
            new_name="count_actions_in_current_day",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="_count_days_in_bot",
            new_name="count_days_in_bot",
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 53, 19, 92355),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 53, 19, 92332),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 19, 53, 19, 94501),
                verbose_name="Время покупки",
            ),
        ),
    ]
