# Generated by Django 4.1.3 on 2022-12-11 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0024_rename__count_actions_profile_count_actions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(default=0, max_length=255, verbose_name="ФИО"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                default="none", max_length=15, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_action_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 23, 21, 7, 980219),
                verbose_name="Дата последней активности",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 23, 21, 7, 980219),
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="datetime_buy",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 23, 21, 7, 985207),
                verbose_name="Время покупки",
            ),
        ),
    ]
