# Generated by Django 4.1.4 on 2022-12-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Дата")),
                ("name", models.CharField(max_length=255, verbose_name="Подборка")),
                (
                    "done",
                    models.BooleanField(
                        default=False, verbose_name="Завершенный обзор"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст поста обзора")),
                (
                    "message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID Сообщения"
                    ),
                ),
                ("datetime_send", models.DateTimeField(verbose_name="Время отправки")),
            ],
            options={
                "verbose_name": "Подборка",
                "verbose_name_plural": "Подборки",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID Сообщения"
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.compilation",
                        verbose_name="Подборка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Текст поста")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_post",
                        to="posts.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        to_field="telegram_id",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост пользователя",
                "verbose_name_plural": "Посты пользователей",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название магазина"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.currency",
                        verbose_name="Валюта магазина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ссылка"
                    ),
                ),
                ("sizes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price_old", models.FloatField(default=0, verbose_name="Старая цена")),
                (
                    "price_new",
                    models.FloatField(blank=True, null=True, verbose_name="Новая цена"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="posts.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в посте",
                "verbose_name_plural": "Товары в посте",
            },
        ),
        migrations.CreateModel(
            name="FinalCompilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Текст ГИДа")),
                (
                    "message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID Сообщения"
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.compilation",
                        verbose_name="Подборка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окончание подборки",
                "verbose_name_plural": "Окончания подборок",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to="post_content", verbose_name="Файл"),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Фотография"),
                            (1, "Видео"),
                            (2, "Аудио"),
                            (3, "Документ"),
                        ],
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="posts.compilation",
                        verbose_name="Компиляция",
                    ),
                ),
                (
                    "final_compilation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="posts.finalcompilation",
                        verbose_name="Гид",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="posts.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
    ]
