# Generated by Django 4.1.4 on 2022-12-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="compilation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="posts.compilation",
                verbose_name="Компиляция",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="final_compilation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="posts.finalcompilation",
                verbose_name="Гид",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="posts.post",
                verbose_name="Пост",
            ),
        ),
    ]
