# Generated by Django 4.1.3 on 2022-12-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_last_action_date_and_more"),
        ("posts", "0002_alter_content_post_userpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="file",
            field=models.FileField(upload_to="post_content", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пользователь",
            ),
        ),
    ]
