# Generated by Django 4.1.3 on 2022-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_content_file_alter_userpost_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalcompilation",
            name="text",
            field=models.TextField(verbose_name="Текст ГИДа"),
        ),
    ]
