# Generated by Django 4.1.3 on 2022-12-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyboard",
            options={},
        ),
    ]
