# Generated by Django 4.1.4 on 2022-12-21 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Время")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Создан пост"),
                            (1, "Отредактирован пост"),
                            (2, "Удален пост"),
                            (3, "Создана подборка"),
                            (4, "Удалена подборка"),
                            (5, "Отредактирована подборка"),
                            (6, "Создан гид"),
                            (7, "Удален гид"),
                            (8, "Отредактирован гид"),
                        ],
                        verbose_name="Тип",
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.compilation",
                        verbose_name="Подборка",
                    ),
                ),
                (
                    "final_compilation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.finalcompilation",
                        verbose_name="Гид",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
