# Generated by Django 4.1.3 on 2022-12-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsuser",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.productsettings",
                verbose_name="Настройки продукт",
            ),
        ),
    ]
