# Generated by Django 4.1.4 on 2022-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator_id",
                    models.BigIntegerField(verbose_name="ИД создателя диплинки"),
                ),
                ("deep_link", models.CharField(max_length=255, verbose_name="Диплинк")),
                ("identifier", models.BigIntegerField(verbose_name="Идентификатор")),
                (
                    "used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
            ],
            options={
                "verbose_name": "Диплинк",
                "verbose_name_plural": "Диплинки",
            },
        ),
    ]
