# Generated by Django 4.1.3 on 2022-12-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_remove_settingsuser_id_alter_settingsuser_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsettings",
            name="id",
        ),
        migrations.RemoveField(
            model_name="settingsuser",
            name="product",
        ),
        migrations.AddField(
            model_name="productsettings",
            name="settings",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="settings.settingsuser",
                verbose_name="Настройки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settingsuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
