# Generated by Django 4.1.3 on 2022-12-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_alter_profile_last_action_date_and_more"),
        ("settings", "0005_alter_settingsuser_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chaneltelegram",
            old_name="name_channel",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="chaneltelegram",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="chanelvk",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пользователь",
            ),
        ),
    ]
