# Generated by Django 4.1.3 on 2022-12-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_alter_profile_last_action_date_and_more"),
        ("settings", "0006_rename_name_channel_chaneltelegram_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="currency",
            field=models.CharField(max_length=4, unique=True, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="settingsuser",
            name="currency",
            field=models.IntegerField(
                choices=[(0, "Валюта магазина"), (1, "Рубли")],
                default=0,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="settingsuser",
            name="rounder",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Уровень округления"
            ),
        ),
        migrations.CreateModel(
            name="CourseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.currency",
                        to_field="currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        to_field="telegram_id",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валют пользователя",
                "verbose_name_plural": "Курсы валют пользователей",
            },
        ),
    ]
