# Generated by Django 4.1.3 on 2022-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0007_alter_currency_currency_alter_settingsuser_currency_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="settingsuser",
            old_name="user",
            new_name="profile",
        ),
    ]
