# Generated by Django 4.1.3 on 2022-12-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_alter_profile_last_action_date_and_more"),
        ("settings", "0008_rename_user_settingsuser_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsuser",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                to_field="telegram_id",
                verbose_name="Пользователь",
            ),
        ),
    ]
