# Generated by Django 4.1.3 on 2022-12-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_alter_settingsuser_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsettings",
            name="settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="product_settings",
                serialize=False,
                to="settings.settingsuser",
                verbose_name="Настройки",
            ),
        ),
        migrations.AlterField(
            model_name="settingsuser",
            name="signature",
            field=models.TextField(blank=True, default="", verbose_name="Подпись"),
        ),
    ]
