# Generated by Django 4.1.3 on 2022-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0010_alter_productsettings_settings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="sign",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Знак валюты"
            ),
        ),
    ]
